/*
 * rustfmt::skip is an unstable attribute being phased out in the future. This
 * is fine for now because we should soon switch to generating bindings from C
 * headers instead of checking in the bindgen output.
 *
 * Wrapping rustfmt::skip in cfg_attr silences the deprecation warning
 */
#![cfg_attr(any(), rustfmt::skip)]
/* automatically generated by rust-bindgen 0.69.5 */
pub const VIRTIO_CONFIG_S_ACKNOWLEDGE: u32 = 1;
pub const VIRTIO_CONFIG_S_DRIVER: u32 = 2;
pub const VIRTIO_CONFIG_S_DRIVER_OK: u32 = 4;
pub const VIRTIO_CONFIG_S_FEATURES_OK: u32 = 8;
pub const VIRTIO_CONFIG_S_NEEDS_RESET: u32 = 64;
pub const VIRTIO_CONFIG_S_FAILED: u32 = 128;
pub const VIRTIO_TRANSPORT_F_START: u32 = 28;
pub const VIRTIO_TRANSPORT_F_END: u32 = 42;
pub const VIRTIO_F_NOTIFY_ON_EMPTY: u32 = 24;
pub const VIRTIO_F_ANY_LAYOUT: u32 = 27;
pub const VIRTIO_F_VERSION_1: u32 = 32;
pub const VIRTIO_F_ACCESS_PLATFORM: u32 = 33;
pub const VIRTIO_F_IOMMU_PLATFORM: u32 = 33;
pub const VIRTIO_F_RING_PACKED: u32 = 34;
pub const VIRTIO_F_IN_ORDER: u32 = 35;
pub const VIRTIO_F_ORDER_PLATFORM: u32 = 36;
pub const VIRTIO_F_SR_IOV: u32 = 37;
pub const VIRTIO_F_NOTIFICATION_DATA: u32 = 38;
pub const VIRTIO_F_NOTIF_CONFIG_DATA: u32 = 39;
pub const VIRTIO_F_RING_RESET: u32 = 40;
pub const VIRTIO_F_ADMIN_VQ: u32 = 41;
pub const VIRTIO_MSG_CONNECT: u32 = 1;
pub const VIRTIO_MSG_DISCONNECT: u32 = 2;
pub const VIRTIO_MSG_DEVICE_INFO: u32 = 3;
pub const VIRTIO_MSG_GET_FEATURES: u32 = 4;
pub const VIRTIO_MSG_SET_FEATURES: u32 = 5;
pub const VIRTIO_MSG_GET_CONFIG: u32 = 6;
pub const VIRTIO_MSG_SET_CONFIG: u32 = 7;
pub const VIRTIO_MSG_GET_CONFIG_GEN: u32 = 8;
pub const VIRTIO_MSG_GET_DEVICE_STATUS: u32 = 9;
pub const VIRTIO_MSG_SET_DEVICE_STATUS: u32 = 10;
pub const VIRTIO_MSG_GET_VQUEUE: u32 = 11;
pub const VIRTIO_MSG_SET_VQUEUE: u32 = 12;
pub const VIRTIO_MSG_RESET_VQUEUE: u32 = 13;
pub const VIRTIO_MSG_EVENT_CONFIG: u32 = 16;
pub const VIRTIO_MSG_EVENT_AVAIL: u32 = 17;
pub const VIRTIO_MSG_EVENT_USED: u32 = 18;
pub const VIRTIO_MSG_MAX: u32 = 18;
pub const VIRTIO_MSG_MAX_SIZE: u32 = 40;
pub const VIRTIO_MSG_TYPE_RESPONSE: u32 = 1;
pub const VIRTIO_MSG_TYPE_VIRTIO: u32 = 0;
pub const VIRTIO_MSG_TYPE_BUS: u32 = 2;
pub const VIRTIO_MSG_FFA_ERROR: u32 = 0;
pub const VIRTIO_MSG_FFA_ACTIVATE: u32 = 1;
pub const VIRTIO_MSG_FFA_DEACTIVATE: u32 = 2;
pub const VIRTIO_MSG_FFA_CONFIGURE: u32 = 3;
pub const VIRTIO_MSG_FFA_AREA_SHARE: u32 = 4;
pub const VIRTIO_MSG_FFA_AREA_UNSHARE: u32 = 5;
pub const VIRTIO_MSG_FFA_VERSION_1_0: u32 = 1;
pub const VIRTIO_MSG_FFA_FEATURE_INDIRECT_MSG_SUPP: u32 = 1;
pub const VIRTIO_MSG_FFA_FEATURE_DIRECT_MSG_SUPP: u32 = 2;
pub const VIRTIO_MSG_FFA_FEATURE_NUM_SHM: u32 = 65280;
pub const VIRTIO_MSG_FFA_AREA_ID_OFFSET: u32 = 56;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_device_info_resp {
    pub device_version: u32,
    pub device_id: u32,
    pub vendor_id: u32,
}
#[test]
fn bindgen_test_layout_get_device_info_resp() {
    const UNINIT: ::core::mem::MaybeUninit<get_device_info_resp> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_device_info_resp>(),
        12usize,
        concat!("Size of: ", stringify!(get_device_info_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<get_device_info_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(get_device_info_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).device_version) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_device_info_resp),
            "::",
            stringify!(device_version)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).device_id) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(get_device_info_resp),
            "::",
            stringify!(device_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).vendor_id) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(get_device_info_resp),
            "::",
            stringify!(vendor_id)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_features {
    pub index: u32,
}
#[test]
fn bindgen_test_layout_get_features() {
    const UNINIT: ::core::mem::MaybeUninit<get_features> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_features>(),
        4usize,
        concat!("Size of: ", stringify!(get_features))
    );
    assert_eq!(
        ::core::mem::align_of::<get_features>(),
        1usize,
        concat!("Alignment of ", stringify!(get_features))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_features),
            "::",
            stringify!(index)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_features_resp {
    pub index: u32,
    pub features: [u64; 4usize],
}
#[test]
fn bindgen_test_layout_get_features_resp() {
    const UNINIT: ::core::mem::MaybeUninit<get_features_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_features_resp>(),
        36usize,
        concat!("Size of: ", stringify!(get_features_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<get_features_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(get_features_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_features_resp),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).features) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(get_features_resp),
            "::",
            stringify!(features)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct set_features {
    pub index: u32,
    pub features: [u64; 4usize],
}
#[test]
fn bindgen_test_layout_set_features() {
    const UNINIT: ::core::mem::MaybeUninit<set_features> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<set_features>(),
        36usize,
        concat!("Size of: ", stringify!(set_features))
    );
    assert_eq!(
        ::core::mem::align_of::<set_features>(),
        1usize,
        concat!("Alignment of ", stringify!(set_features))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(set_features),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).features) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(set_features),
            "::",
            stringify!(features)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct set_features_resp {
    pub index: u32,
    pub features: [u64; 4usize],
}
#[test]
fn bindgen_test_layout_set_features_resp() {
    const UNINIT: ::core::mem::MaybeUninit<set_features_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<set_features_resp>(),
        36usize,
        concat!("Size of: ", stringify!(set_features_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<set_features_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(set_features_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(set_features_resp),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).features) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(set_features_resp),
            "::",
            stringify!(features)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_config {
    pub offset: [u8; 3usize],
    pub size: u8,
}
#[test]
fn bindgen_test_layout_get_config() {
    const UNINIT: ::core::mem::MaybeUninit<get_config> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_config>(),
        4usize,
        concat!("Size of: ", stringify!(get_config))
    );
    assert_eq!(
        ::core::mem::align_of::<get_config>(),
        1usize,
        concat!("Alignment of ", stringify!(get_config))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).offset) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_config),
            "::",
            stringify!(offset)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        3usize,
        concat!(
            "Offset of field: ",
            stringify!(get_config),
            "::",
            stringify!(size)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_config_resp {
    pub offset: [u8; 3usize],
    pub size: u8,
    pub data: [u64; 4usize],
}
#[test]
fn bindgen_test_layout_get_config_resp() {
    const UNINIT: ::core::mem::MaybeUninit<get_config_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_config_resp>(),
        36usize,
        concat!("Size of: ", stringify!(get_config_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<get_config_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(get_config_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).offset) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_config_resp),
            "::",
            stringify!(offset)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        3usize,
        concat!(
            "Offset of field: ",
            stringify!(get_config_resp),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).data) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(get_config_resp),
            "::",
            stringify!(data)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct set_config {
    pub offset: [u8; 3usize],
    pub size: u8,
    pub data: [u64; 4usize],
}
#[test]
fn bindgen_test_layout_set_config() {
    const UNINIT: ::core::mem::MaybeUninit<set_config> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<set_config>(),
        36usize,
        concat!("Size of: ", stringify!(set_config))
    );
    assert_eq!(
        ::core::mem::align_of::<set_config>(),
        1usize,
        concat!("Alignment of ", stringify!(set_config))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).offset) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(set_config),
            "::",
            stringify!(offset)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        3usize,
        concat!(
            "Offset of field: ",
            stringify!(set_config),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).data) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(set_config),
            "::",
            stringify!(data)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct set_config_resp {
    pub offset: [u8; 3usize],
    pub size: u8,
    pub data: [u64; 4usize],
}
#[test]
fn bindgen_test_layout_set_config_resp() {
    const UNINIT: ::core::mem::MaybeUninit<set_config_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<set_config_resp>(),
        36usize,
        concat!("Size of: ", stringify!(set_config_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<set_config_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(set_config_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).offset) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(set_config_resp),
            "::",
            stringify!(offset)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        3usize,
        concat!(
            "Offset of field: ",
            stringify!(set_config_resp),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).data) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(set_config_resp),
            "::",
            stringify!(data)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_config_gen_resp {
    pub generation: u32,
}
#[test]
fn bindgen_test_layout_get_config_gen_resp() {
    const UNINIT: ::core::mem::MaybeUninit<get_config_gen_resp> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_config_gen_resp>(),
        4usize,
        concat!("Size of: ", stringify!(get_config_gen_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<get_config_gen_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(get_config_gen_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).generation) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_config_gen_resp),
            "::",
            stringify!(generation)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_device_status_resp {
    pub status: u32,
}
#[test]
fn bindgen_test_layout_get_device_status_resp() {
    const UNINIT: ::core::mem::MaybeUninit<get_device_status_resp> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_device_status_resp>(),
        4usize,
        concat!("Size of: ", stringify!(get_device_status_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<get_device_status_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(get_device_status_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).status) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_device_status_resp),
            "::",
            stringify!(status)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct set_device_status {
    pub status: u32,
}
#[test]
fn bindgen_test_layout_set_device_status() {
    const UNINIT: ::core::mem::MaybeUninit<set_device_status> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<set_device_status>(),
        4usize,
        concat!("Size of: ", stringify!(set_device_status))
    );
    assert_eq!(
        ::core::mem::align_of::<set_device_status>(),
        1usize,
        concat!("Alignment of ", stringify!(set_device_status))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).status) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(set_device_status),
            "::",
            stringify!(status)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_vqueue {
    pub index: u32,
}
#[test]
fn bindgen_test_layout_get_vqueue() {
    const UNINIT: ::core::mem::MaybeUninit<get_vqueue> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_vqueue>(),
        4usize,
        concat!("Size of: ", stringify!(get_vqueue))
    );
    assert_eq!(
        ::core::mem::align_of::<get_vqueue>(),
        1usize,
        concat!("Alignment of ", stringify!(get_vqueue))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_vqueue),
            "::",
            stringify!(index)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct get_vqueue_resp {
    pub index: u32,
    pub max_size: u32,
    pub size: u32,
    pub descriptor_addr: u64,
    pub driver_addr: u64,
    pub device_addr: u64,
}
#[test]
fn bindgen_test_layout_get_vqueue_resp() {
    const UNINIT: ::core::mem::MaybeUninit<get_vqueue_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<get_vqueue_resp>(),
        36usize,
        concat!("Size of: ", stringify!(get_vqueue_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<get_vqueue_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(get_vqueue_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(get_vqueue_resp),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).max_size) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(get_vqueue_resp),
            "::",
            stringify!(max_size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(get_vqueue_resp),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).descriptor_addr) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(get_vqueue_resp),
            "::",
            stringify!(descriptor_addr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).driver_addr) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(get_vqueue_resp),
            "::",
            stringify!(driver_addr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).device_addr) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(get_vqueue_resp),
            "::",
            stringify!(device_addr)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct set_vqueue {
    pub index: u32,
    pub unused: u32,
    pub size: u32,
    pub descriptor_addr: u64,
    pub driver_addr: u64,
    pub device_addr: u64,
}
#[test]
fn bindgen_test_layout_set_vqueue() {
    const UNINIT: ::core::mem::MaybeUninit<set_vqueue> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<set_vqueue>(),
        36usize,
        concat!("Size of: ", stringify!(set_vqueue))
    );
    assert_eq!(
        ::core::mem::align_of::<set_vqueue>(),
        1usize,
        concat!("Alignment of ", stringify!(set_vqueue))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).unused) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue),
            "::",
            stringify!(unused)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).descriptor_addr) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue),
            "::",
            stringify!(descriptor_addr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).driver_addr) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue),
            "::",
            stringify!(driver_addr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).device_addr) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue),
            "::",
            stringify!(device_addr)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct set_vqueue_resp {
    pub index: u32,
    pub unused: u32,
    pub size: u32,
    pub descriptor_addr: u64,
    pub driver_addr: u64,
    pub device_addr: u64,
}
#[test]
fn bindgen_test_layout_set_vqueue_resp() {
    const UNINIT: ::core::mem::MaybeUninit<set_vqueue_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<set_vqueue_resp>(),
        36usize,
        concat!("Size of: ", stringify!(set_vqueue_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<set_vqueue_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(set_vqueue_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue_resp),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).unused) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue_resp),
            "::",
            stringify!(unused)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue_resp),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).descriptor_addr) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue_resp),
            "::",
            stringify!(descriptor_addr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).driver_addr) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue_resp),
            "::",
            stringify!(driver_addr)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).device_addr) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(set_vqueue_resp),
            "::",
            stringify!(device_addr)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct reset_vqueue {
    pub index: u32,
}
#[test]
fn bindgen_test_layout_reset_vqueue() {
    const UNINIT: ::core::mem::MaybeUninit<reset_vqueue> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<reset_vqueue>(),
        4usize,
        concat!("Size of: ", stringify!(reset_vqueue))
    );
    assert_eq!(
        ::core::mem::align_of::<reset_vqueue>(),
        1usize,
        concat!("Alignment of ", stringify!(reset_vqueue))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(reset_vqueue),
            "::",
            stringify!(index)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct event_config {
    pub status: u32,
    pub offset: [u8; 3usize],
    pub size: u8,
    pub value: [u32; 4usize],
}
#[test]
fn bindgen_test_layout_event_config() {
    const UNINIT: ::core::mem::MaybeUninit<event_config> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<event_config>(),
        24usize,
        concat!("Size of: ", stringify!(event_config))
    );
    assert_eq!(
        ::core::mem::align_of::<event_config>(),
        1usize,
        concat!("Alignment of ", stringify!(event_config))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).status) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(event_config),
            "::",
            stringify!(status)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).offset) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(event_config),
            "::",
            stringify!(offset)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        7usize,
        concat!(
            "Offset of field: ",
            stringify!(event_config),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).value) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(event_config),
            "::",
            stringify!(value)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct event_avail {
    pub index: u32,
    pub next_offset: u32,
    pub next_wrap: u32,
}
#[test]
fn bindgen_test_layout_event_avail() {
    const UNINIT: ::core::mem::MaybeUninit<event_avail> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<event_avail>(),
        12usize,
        concat!("Size of: ", stringify!(event_avail))
    );
    assert_eq!(
        ::core::mem::align_of::<event_avail>(),
        1usize,
        concat!("Alignment of ", stringify!(event_avail))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(event_avail),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).next_offset) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(event_avail),
            "::",
            stringify!(next_offset)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).next_wrap) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(event_avail),
            "::",
            stringify!(next_wrap)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct event_used {
    pub index: u32,
}
#[test]
fn bindgen_test_layout_event_used() {
    const UNINIT: ::core::mem::MaybeUninit<event_used> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<event_used>(),
        4usize,
        concat!("Size of: ", stringify!(event_used))
    );
    assert_eq!(
        ::core::mem::align_of::<event_used>(),
        1usize,
        concat!("Alignment of ", stringify!(event_used))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(event_used),
            "::",
            stringify!(index)
        )
    );
}
#[repr(C, packed)]
#[derive(Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct virtio_msg {
    pub type_: u8,
    pub id: u8,
    pub dev_id: u16,
    pub __bindgen_anon_1: virtio_msg__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub union virtio_msg__bindgen_ty_1 {
    pub payload_u8: [u8; 36usize],
    pub get_device_info_resp: get_device_info_resp,
    pub get_features: get_features,
    pub get_features_resp: get_features_resp,
    pub set_features: set_features,
    pub set_features_resp: set_features_resp,
    pub get_config: get_config,
    pub get_config_resp: get_config_resp,
    pub set_config: set_config,
    pub set_config_resp: set_config_resp,
    pub get_config_gen_resp: get_config_gen_resp,
    pub get_device_status_resp: get_device_status_resp,
    pub set_device_status: set_device_status,
    pub get_vqueue: get_vqueue,
    pub get_vqueue_resp: get_vqueue_resp,
    pub set_vqueue: set_vqueue,
    pub set_vqueue_resp: set_vqueue_resp,
    pub reset_vqueue: reset_vqueue,
    pub event_config: event_config,
    pub event_avail: event_avail,
    pub event_used: event_used,
}
#[test]
fn bindgen_test_layout_virtio_msg__bindgen_ty_1() {
    const UNINIT: ::core::mem::MaybeUninit<virtio_msg__bindgen_ty_1> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<virtio_msg__bindgen_ty_1>(),
        36usize,
        concat!("Size of: ", stringify!(virtio_msg__bindgen_ty_1))
    );
    assert_eq!(
        ::core::mem::align_of::<virtio_msg__bindgen_ty_1>(),
        1usize,
        concat!("Alignment of ", stringify!(virtio_msg__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).payload_u8) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(payload_u8)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_device_info_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_device_info_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_features) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_features)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_features_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_features_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).set_features) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(set_features)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).set_features_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(set_features_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_config) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_config)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_config_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_config_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).set_config) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(set_config)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).set_config_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(set_config_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_config_gen_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_config_gen_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_device_status_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_device_status_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).set_device_status) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(set_device_status)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_vqueue) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_vqueue)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).get_vqueue_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(get_vqueue_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).set_vqueue) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(set_vqueue)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).set_vqueue_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(set_vqueue_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).reset_vqueue) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(reset_vqueue)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).event_config) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(event_config)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).event_avail) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(event_avail)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).event_used) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg__bindgen_ty_1),
            "::",
            stringify!(event_used)
        )
    );
}
#[test]
fn bindgen_test_layout_virtio_msg() {
    const UNINIT: ::core::mem::MaybeUninit<virtio_msg> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<virtio_msg>(),
        40usize,
        concat!("Size of: ", stringify!(virtio_msg))
    );
    assert_eq!(
        ::core::mem::align_of::<virtio_msg>(),
        1usize,
        concat!("Alignment of ", stringify!(virtio_msg))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).id) as usize - ptr as usize },
        1usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).dev_id) as usize - ptr as usize },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg),
            "::",
            stringify!(dev_id)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct bus_activate {
    pub driver_version: u32,
}
#[test]
fn bindgen_test_layout_bus_activate() {
    const UNINIT: ::core::mem::MaybeUninit<bus_activate> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<bus_activate>(),
        4usize,
        concat!("Size of: ", stringify!(bus_activate))
    );
    assert_eq!(
        ::core::mem::align_of::<bus_activate>(),
        1usize,
        concat!("Alignment of ", stringify!(bus_activate))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).driver_version) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_activate),
            "::",
            stringify!(driver_version)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct bus_activate_resp {
    pub device_version: u32,
    pub features: u64,
    pub num: u64,
}
#[test]
fn bindgen_test_layout_bus_activate_resp() {
    const UNINIT: ::core::mem::MaybeUninit<bus_activate_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<bus_activate_resp>(),
        20usize,
        concat!("Size of: ", stringify!(bus_activate_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<bus_activate_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(bus_activate_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).device_version) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_activate_resp),
            "::",
            stringify!(device_version)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).features) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_activate_resp),
            "::",
            stringify!(features)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).num) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_activate_resp),
            "::",
            stringify!(num)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct bus_configure {
    pub features: u64,
}
#[test]
fn bindgen_test_layout_bus_configure() {
    const UNINIT: ::core::mem::MaybeUninit<bus_configure> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<bus_configure>(),
        8usize,
        concat!("Size of: ", stringify!(bus_configure))
    );
    assert_eq!(
        ::core::mem::align_of::<bus_configure>(),
        1usize,
        concat!("Alignment of ", stringify!(bus_configure))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).features) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_configure),
            "::",
            stringify!(features)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct bus_configure_resp {
    pub features: u64,
}
#[test]
fn bindgen_test_layout_bus_configure_resp() {
    const UNINIT: ::core::mem::MaybeUninit<bus_configure_resp> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<bus_configure_resp>(),
        8usize,
        concat!("Size of: ", stringify!(bus_configure_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<bus_configure_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(bus_configure_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).features) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_configure_resp),
            "::",
            stringify!(features)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct bus_area_share {
    pub area_id: u32,
    pub mem_handle: u64,
}
#[test]
fn bindgen_test_layout_bus_area_share() {
    const UNINIT: ::core::mem::MaybeUninit<bus_area_share> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<bus_area_share>(),
        12usize,
        concat!("Size of: ", stringify!(bus_area_share))
    );
    assert_eq!(
        ::core::mem::align_of::<bus_area_share>(),
        1usize,
        concat!("Alignment of ", stringify!(bus_area_share))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).area_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_area_share),
            "::",
            stringify!(area_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).mem_handle) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_area_share),
            "::",
            stringify!(mem_handle)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct bus_area_share_resp {
    pub area_id: u32,
}
#[test]
fn bindgen_test_layout_bus_area_share_resp() {
    const UNINIT: ::core::mem::MaybeUninit<bus_area_share_resp> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<bus_area_share_resp>(),
        4usize,
        concat!("Size of: ", stringify!(bus_area_share_resp))
    );
    assert_eq!(
        ::core::mem::align_of::<bus_area_share_resp>(),
        1usize,
        concat!("Alignment of ", stringify!(bus_area_share_resp))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).area_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_area_share_resp),
            "::",
            stringify!(area_id)
        )
    );
}
#[repr(C, packed)]
#[derive(Debug, Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct bus_area_unshare {
    pub area_id: u32,
    pub mem_handle: u64,
}
#[test]
fn bindgen_test_layout_bus_area_unshare() {
    const UNINIT: ::core::mem::MaybeUninit<bus_area_unshare> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<bus_area_unshare>(),
        12usize,
        concat!("Size of: ", stringify!(bus_area_unshare))
    );
    assert_eq!(
        ::core::mem::align_of::<bus_area_unshare>(),
        1usize,
        concat!("Alignment of ", stringify!(bus_area_unshare))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).area_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_area_unshare),
            "::",
            stringify!(area_id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).mem_handle) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(bus_area_unshare),
            "::",
            stringify!(mem_handle)
        )
    );
}
#[repr(C, packed)]
#[derive(Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub struct virtio_msg_ffa {
    pub type_: u8,
    pub id: u8,
    pub unused: u16,
    pub __bindgen_anon_1: virtio_msg_ffa__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone, zerocopy :: FromBytes, zerocopy :: Immutable)]
pub union virtio_msg_ffa__bindgen_ty_1 {
    pub payload_u8: [u8; 36usize],
    pub bus_activate: bus_activate,
    pub bus_activate_resp: bus_activate_resp,
    pub bus_configure: bus_configure,
    pub bus_configure_resp: bus_configure_resp,
    pub bus_area_share: bus_area_share,
    pub bus_area_share_resp: bus_area_share_resp,
    pub bus_area_unshare: bus_area_unshare,
}
#[test]
fn bindgen_test_layout_virtio_msg_ffa__bindgen_ty_1() {
    const UNINIT: ::core::mem::MaybeUninit<virtio_msg_ffa__bindgen_ty_1> =
        ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<virtio_msg_ffa__bindgen_ty_1>(),
        36usize,
        concat!("Size of: ", stringify!(virtio_msg_ffa__bindgen_ty_1))
    );
    assert_eq!(
        ::core::mem::align_of::<virtio_msg_ffa__bindgen_ty_1>(),
        1usize,
        concat!("Alignment of ", stringify!(virtio_msg_ffa__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).payload_u8) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(payload_u8)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).bus_activate) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(bus_activate)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).bus_activate_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(bus_activate_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).bus_configure) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(bus_configure)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).bus_configure_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(bus_configure_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).bus_area_share) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(bus_area_share)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).bus_area_share_resp) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(bus_area_share_resp)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).bus_area_unshare) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa__bindgen_ty_1),
            "::",
            stringify!(bus_area_unshare)
        )
    );
}
#[test]
fn bindgen_test_layout_virtio_msg_ffa() {
    const UNINIT: ::core::mem::MaybeUninit<virtio_msg_ffa> = ::core::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::core::mem::size_of::<virtio_msg_ffa>(),
        40usize,
        concat!("Size of: ", stringify!(virtio_msg_ffa))
    );
    assert_eq!(
        ::core::mem::align_of::<virtio_msg_ffa>(),
        1usize,
        concat!("Alignment of ", stringify!(virtio_msg_ffa))
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).id) as usize - ptr as usize },
        1usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe { ::core::ptr::addr_of!((*ptr).unused) as usize - ptr as usize },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(virtio_msg_ffa),
            "::",
            stringify!(unused)
        )
    );
}
