#![no_std]
#![allow(non_camel_case_types)]
#![feature(cfg_version)]
// C string byte counts were stabilized in Rust 1.79
#![cfg_attr(not(version("1.79")), feature(cstr_count_bytes))]
// C string literals were stabilized in Rust 1.77
#![cfg_attr(not(version("1.77")), feature(c_str_literals))]
// unsigned_is_multiple_of feature was added in Rust 1.82
#![cfg_attr(version("1.82"), feature(unsigned_is_multiple_of))]

mod err;
mod hal;
mod pci;
mod vsock;

// TODO: Follow the normal bindgen pattern once we find a suitable location for
// the header files that the virtio-msg bindings were generated from. Current
// bindings were generated by building generic-arm64-virt-test-debug with
// aosp/3390803/25 applied and used prebuilt bindgen 0.69.5.
#[allow(clippy::upper_case_acronyms)]
#[allow(unused)]
#[allow(non_camel_case_types)]
#[allow(non_upper_case_globals)]
#[rustfmt::skip]
#[path = "bindings.rs"]
mod sys;

pub use err::Error;
pub use pci::pci_init_mmio;
